name: Run build avif enc with musl

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk update && apk add alpine-sdk cmake ninja musl-dev git nasm libjpeg-turbo-dev libpng-dev zlib-static libpng-static libjpeg-turbo-static meson perl

    - name: Clone libavif repository
      run: |
        git clone --depth 1 https://github.com/AOMediaCodec/libavif.git

    - name: Build libavif
      run: |
        cd libavif
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DAVIF_CODEC_AOM=LOCAL -DAVIF_CODEC_DAV1D=LOCAL -DAVIF_LIBYUV=LOCAL -DAVIF_BUILD_APPS=ON -DCMAKE_EXE_LINKER_FLAGS="-static" -DPNG_LIBRARY=/usr/lib/libpng16.a -DZLIB_LIBRARY=/lib/libz.a -DJPEG_LIBRARY=/usr/lib/libjpeg.a ..
        ninja

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: avif-binaries
        path: |
          libavif/build/avifenc
          libavif/build/avifdec

    - name: Copy binaries to static_bin directory
      run: |
        ls -la
        mkdir -p static_bin/
        cp libavif/build/avifenc static_bin/
        cp libavif/build/avifdec static_bin/
        ls -la

    - name: Commit and push binaries
      run: |
        git config --global user.name 'PR0LAPSE'
        git config --global user.email '117679376+PR0LAPSE@users.noreply.github.com'
        git add static_bin/
        git commit -m "Add compiled binaries" || echo "No changes to commit"
        git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/PR0LAPSE/avifenc.git main
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      working-directory: /github/workspace
